[package]
name = "shadowai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
futures = "0.3.33"
glob = "0.3.4"
rig = "0.40.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = [
  "macros",
  "rt-multi-thread",
  "io-std",
  "io-util",
] }
tokio-stream = "0.1.19"
tokio-util = { version = "0.7.19", features = ["codec"] }
