[workspace]
members = [
  "crates/shadowai-agent",
  "crates/shadowai-filesystem",
  "crates/shadowai-shell",
  "crates/shadowai-tools",
]

[package]
name = "shadowai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
directories = "6.0.0"
shadowai-agent.workspace = true
shadowai-filesystem.workspace = true
shadowai-shell.workspace = true
shadowai-tools.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "time",
  "local-time",
] }

[workspace.dependencies]
shadowai-agent = { path = "crates/shadowai-agent" }
shadowai-filesystem = { path = "crates/shadowai-filesystem" }
shadowai-shell = { path = "crates/shadowai-shell" }
shadowai-tools = { path = "crates/shadowai-tools" }

anyhow = "1.0.104"
futures = "0.3.33"
glob = "0.3.4"
rig = "0.40.0"
schemars = "1.2.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
test_dir = "0.2.0"
thiserror = "2.0.19"
tokio = "1.53.1"
tokio-stream = "0.1.19"
tokio-util = "0.7.19"
