[package]
name = "shadowai-filesystem"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["fs", "io-util"] }
thiserror.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "fs",
  "io-util",
] }
anyhow.workspace = true
test_dir.workspace = true
