[package]
name = "shadowai-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
rig.workspace = true
glob.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
shadowai-filesystem.workspace = true
shadowai-shell.workspace = true
schemars.workspace = true
